# Generated by Django 4.1 on 2023-12-22 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Model",
            new_name="JobModel",
        ),
    ]
