# Generated by Django 5.0 on 2023-12-23 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_rename_model_jobmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobmodel",
            old_name="companyUrl",
            new_name="companyURL",
        ),
    ]
