# Generated by Django 5.0 on 2023-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_rename_jobid_jobmodel_jobid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobmodel",
            name="jobId",
            field=models.CharField(max_length=100),
        ),
    ]
